name: cognito
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4"

dependencies:
  animated_text_kit: ^4.2.2
  build_runner: ^2.4.11
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
  flutter_map: ^7.0.2
  url_launcher: ^6.1.10
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.6
  flutter_markdown: ^0.7.3
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.3
  google_sign_in: ^6.2.1
  http: ^1.2.1
  http_parser: ^4.0.2
  iconsax: ^0.0.8
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  # just_audio: ^0.9.39
  lottie: ^3.1.0
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  permission_handler: any
  provider: ^6.1.2
  simple_ripple_animation: ^0.1.0
  uuid: ^4.3.3
  image: ^4.0.19

dependency_overrides:
  _fe_analyzer_shared: ^77.0.0
  analyzer: ^7.0.0
  archive: ^4.0.1
  async: ^2.12.0
  boolean_selector: ^2.1.2
  characters: ^1.4.0
  clock: ^1.1.2
  collection: ^1.19.1
  dart_style: ^3.0.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  source_span: ^1.10.1
  string_scanner: ^1.4.0
  test_api: ^0.7.4
  vm_service: ^15.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic